services:
  - type: web
    name: alnafar-store
    env: node
    buildCommand: npm install; npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
